### ISSUE TITLE
MELSEC iQ-F FX5 series?

### ISSUE THREAD

**Issue by flacohenao** [Steve-Mcl/node-red-contrib-mcprotocol#1]
Hey Steve!!!

So... just to make it clear, this supports the MELSEC iQ-F FX5 series?

Dont you have the code to be imported on node, not just node-red?

bests,

**Comment by Steve-Mcl** [comment]
this node is purely for node-red. I'm a few days I will be updating a separate library that is just for node. 

I don't have access to that particular PLC but if it supports MC Protocol, I don't see why it wouldn't work. 

would you be willing to perform some tests with this PLC when I get the separate nodejs library updated?

**Comment by flacohenao** [comment]
For sure!!
let me know when your node Library is ready to test it out!

**Comment by flacohenao** [comment]
@Steve-Mcl Hey steve! how the thing going?

**Comment by Steve-Mcl** [comment]
Hey @flacohenao I have the mcprotocol code i use in a separate lib [here](https://github.com/Steve-Mcl/node-red-contrib-mcprotocol) 

If you could test that and see if it works for you & feedback please?

**Comment by Steve-Mcl** [comment]
Closing due to lack of feedback
