### ISSUE TITLE
TypeError: The "msecs" argument must be of type number. Received type string ('1000')

### ISSUE THREAD

**Issue by serafimdasaudade** [Steve-Mcl/node-red-contrib-mcprotocol#10]
I don't understand the reason for this error. 
node-red version: 1.2.7

![image](https://user-images.githubusercontent.com/8669441/106201704-be503d00-61b0-11eb-8cfb-22bb7236fb95.png)

Best regards,

**Comment by Steve-Mcl** [comment]
Hi, I have just pushed an update (v1.2.1) that hopefully fixes this. 

Would you please update and test (close if fixed please)

cheers.

**Comment by serafimdasaudade** [comment]
Tks. It's resolve.

Best Regards,
