### ISSUE TITLE
Not connected after PLC reset

### ISSUE THREAD

**Issue by YK934** [Steve-Mcl/node-red-contrib-mcprotocol#2]
Hi Steve,

Firstly, thank you for developing this node, this is very useful. I am testing this on few q03udvcpu and a fx5uc. Those q03udvcpu, monitoring my factory productivity and store to database 24/7 and no problem most of time. But every time reset those PLC, connection could not recover and only way to reconnect is resetting the node-red flow.  Other situation is when disconnect the PLC, it recover connection if disconnection is short duration but not if it is long, say 30sec.

Is it possible to make reconnect automatically after reset PLC? 3E frame used for both PLC and version is 1.1.3 for q03udv and 1.1.7 for fx5uc. 

Thanks,

![nodered_afer_reset_PLC](https://user-images.githubusercontent.com/75152229/100493494-02a86800-3183-11eb-876c-cc686aef8560.jpg)
![nodered_reset_flow](https://user-images.githubusercontent.com/75152229/100493497-0936df80-3183-11eb-99c6-2d2cf3781326.jpg)

**Comment by Steve-Mcl** [comment]
Hi, are you using UDP or TCP? 

Mitsubishi TCP, in my experience, is notoriously unreliable. 

If you are using TCP, I would recommend first trying UDP (4e if possible) to see if that improves reconnection.

2nd, have you tried to disconnect then reconnect by sending a special msg to the MC READ node?  Info is in the built help.  You could create an automatic recovery in your flow.

**Comment by YK934** [comment]
Hi Steve, Yes, once switch to UDP, they work ok. You already mentioned about UDP 4E on README, I didn't read carefully.:p Thank you for your reply.
