### ISSUE TITLE
Compatibility of Node-Red MCProtocol Node for Mitsubishi IQR Series

### ISSUE THREAD

**Issue by wenshyan** [Steve-Mcl/node-red-contrib-mcprotocol#20]
Hello @Steve-Mcl , 

I would like to ask if the node-red node contributed here for Mitsubishi PLCs are compatible with the new Mitsubishi IQR Series? 

We would like to know if you have tested this before?

**Comment by Steve-Mcl** [comment]
I am afraid I o longer have access to Mit PLCs

If I recall from my previous role, yes it did work with the iQR PLCs

Put simply, if a mit PLC supports MC Protocol, in theory, this node should work with it.
