### ISSUE TITLE
Read Mitsubishi FX5U to Node-RED 

### ISSUE THREAD

**Issue by axxy2021** [Steve-Mcl/node-red-contrib-mcprotocol#21]
HI ,i have make connection between mitsubishi fx5u to node-red
but how can read multiple addresses at once, just like FINS-Read

**Comment by mrfy** [comment]
@axxy2021 did you find solution for read multiple? Thanks

**Comment by axxy2021** [comment]
you may find your answe in this&nbsp;article
https://github.com/Steve-Mcl/node-red-contrib-mcprotocol/blob/master/mcprotocol/README.md








article

愛ししや
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Steve-Mcl/node-red-contrib-mcprotocol"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月5日(星期四) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Steve-Mcl/node-red-contrib-mcprotocol] Read Mitsubishi FX5U to Node-RED  (Issue #21)





 
@axxy2021 did you find solution for read multiple? Thanks
