### ISSUE TITLE
Configure the PLC

### ISSUE THREAD

**Issue by kowiste** [Steve-Mcl/node-red-contrib-mcprotocol#4]
Hi , I arrive here from plcpeople/mcprotocol
I'm trying to create a Golang library for mc protocol, first I want to use other library to be sure the plc configuration and use it like a base, but never use Mitsubishi,  could you pass me any documentation/video to configure the plc, I have a borrow IQ-R08 in which I try to configure in the module parameter the communication but cant figure it out what to do.

Thanks

**Comment by Steve-Mcl** [comment]
Hi, unfortunately I am not able to assist directly as I don't have access to an IQR PLC until January. 

There is plenty of info on the internet if you search. 

However, this might get you close...

https://docs.devicewise.com/Content/Products/GatewayDevelopersGuide/Configuring-an-iQ-R-CPU-with-Built-in-Ethernet.htm

**Comment by kowiste** [comment]
Thanks , I will take a look, i f I find the way to do it i will post it here so future person can use it.

**Comment by Steve-Mcl** [comment]
@Kowiste  please do. i will close this issue for now.
