### ISSUE TITLE
Please update node descriptions

### ISSUE THREAD

**Issue by jinx17** [Steve-Mcl/node-red-contrib-mcprotocol#7]
Hi,
It would be nice if you can update node "How to use" description with some examples.
These are my recomendations.

### READING VALUES from PLC:

SETTING MC-READ node
use msg.topic as address

HOW TO READ VALUES:
Trigger function node with this settings to get values of X0 ... X15 inputs.
In this example X0 is the first address to read, 16 is length of data to receive
msg.topic="X0,16" msg.payload="" //To nima vpliva return msg;

### WRITING VALUES to PLC:

SETTING MC-WRITE node
use msg.topic as address
use msg.payload as values to write into PLC

HOW TO WRITE VALUES:
Trigger function node with settings like this
//1st option is using address with length --> define as many values as stated in address length (in my example 2 is length msg.topic="D552,2" msg.payload = [666,777] //2nd option is using address array and values array msg.topic=["D552","D558"] msg.payload = [666,777] //3rd option - setting only one value - address is string, value is number msg.topic="D552" msg.payload = 1234
Regards,
Jinx

**Comment by Steve-Mcl** [comment]
there are examples in the built in documentation...

e.g.. Read node built in help...
![image](https://user-images.githubusercontent.com/44235289/106038783-4579b400-60d0-11eb-9e63-8e3d96bd919e.png)


but sure, I can look to add more in the readme

**Comment by jinx17** [comment]
Hi,
oh, now I understand. Sorry. I missed this totally (I did eyescan this doc, but didn't catch the meaning of it :(  ! 
I am also not a SW programmer and sometimes I have problems decifering such descriptions. Mostly I learn by doing, and examples help me most (examples provided do telll a lot, but are a bit too advanced for a total novice in Mitsubishi and MCprotocol). BTW, As you can tell, English is not my mother language.

A request: Please make text "Address format" BOLD and in RED color, so it is more obvious (for a guy like me :) 
Also add to the examples a simple:
- D5,3 (three consecutive addresses D5,D6 and D7)
- D5.3 (bit nr 3 of D5)

I don't understand the meaning and function of Digit specifier.

Thank you!
