### ISSUE TITLE
Timeout should be number - my sollution

### ISSUE THREAD

**Issue by jinx17** [Steve-Mcl/node-red-contrib-mcprotocol#9]
Hi,
when setting timeout in settings I get error when I deploy, that timeout should be number not string ie "1000".

Sollution (in my opinion):
in file connection.js I use function Number() to tell this variable is getting number, not string.
this.options.timeout = Number(config.timeout) || 1000;
Best regards,
Jinx

**Comment by Steve-Mcl** [comment]
Hi, thanks for this. I personally haven't seen this issue. 

Can you provide a bit more info around your system?

**Comment by jinx17** [comment]
Hi,
sure.
Node-red is running on DietPi (Stripped down Linux OS with great care about file R/W) on a RPi4.
This is the error I get:
"TypeError: The "msecs" argument must be of type number. Received type string ('1000')"

**Comment by Steve-Mcl** [comment]
Hi, I pushed a fix for this. Please update & test. V1.2.1 now in flow library

**Comment by jinx17** [comment]
Great. It works. No more error of getting string and not a number. 
Thanks.
